name = "RoutingNetworksPotato"
uuid = "a24f460d-c78e-41ec-a4f0-23a05e4df611"
authors = ["OwOIamNoob <21020205@vnu.edu.vn>"]
version = "0.1.0"

[deps]
CSFML = "538df835-4bef-5bfa-b281-4025a4f7e8ff"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LibExpat = "522f3ed2-3f36-55e3-b6df-e94fee9b0c07"
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
NearestNeighbors = "b8a86587-4115-5ab1-83bc-aa920d37bbce"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
